#!/bin/bash

if [[ $(systemctl is-active docker) == "active" ]]; then
  IMAGE=$1
  COMMAND="$2 $3 $4 $5 $6 $7 $8 $9"
  
  docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/opt \
    -w /opt $IMAGE /bin/bash -c "$COMMAND"
else
  echo "Docker is not installed or not running!."
  exit 1
fi
